defaultPlacement: end
enableVersioning: true
handle: newsletterIndex
name: 'Newsletter Index'
propagationMethod: all
siteSettings:
  5667283f-37d8-4356-b040-3a9ce12ff30d: # Esperance Historical Museum
    enabledByDefault: true
    hasUrls: true
    template: newsletter/index
    uriFormat: newsletters
type: single
