fieldLayouts:
  2c71049d-f606-472b-b691-71f4ba58d88b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 56cc364f-7157-4115-863a-ff5d2afbfb0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d967ad9-7e46-4156-a765-597a9136ca13 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72dd4388-9937-48cc-8c03-c8ae6040102b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3688768f-2745-4809-9fa3-89729c389bfd
        userCondition: null
handle: exhibitsIndex
hasTitleField: true
name: 'Exhibits Index'
section: 0b3d7006-f110-425d-98b2-981c3e45001f # Exhibits Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
