fieldLayouts:
  faac35d5-78fc-4f7b-9505-44d40a22c7cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b89be628-4244-4cfa-b721-125e748f88ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c89fd4fe-41a5-4c5b-b297-949b41689e8e
        userCondition: null
handle: newsletterIndex
hasTitleField: true
name: 'Newsletter Index'
section: ff63d69e-8aac-4f7f-b5f0-a4f5dc28462f # Newsletter Index
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
