defaultPlacement: end
enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  5667283f-37d8-4356-b040-3a9ce12ff30d: # Esperance Historical Museum
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
