columnSuffix: null
contentColumnType: string
fieldGroup: bfe94fef-4424-4d78-b059-5f64bdeecc01 # Images
handle: newsImage
instructions: null
name: 'Post Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:aee9fd99-7535-4cc1-a3fb-24d20d2a3852' # News Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:aee9fd99-7535-4cc1-a3fb-24d20d2a3852' # News Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:aee9fd99-7535-4cc1-a3fb-24d20d2a3852' # News Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
