columnSuffix: phrwtxea
contentColumnType: text
fieldGroup: bfe94fef-4424-4d78-b059-5f64bdeecc01 # Images
handle: optimizedLandscape
instructions: null
name: 'Optimized Landscape'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: false
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - siteImages
        - '*'
  variants:
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '8'
        -
          - aspectRatioY
          - '5'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
