columnSuffix: pywxiuif
contentColumnType: text
fieldGroup: 2f8248ae-57e7-4959-a9bb-606ed57cdc97 # Books
handle: storageLocation
instructions: null
name: 'Storage Location'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
