defaultPlacement: end
enableVersioning: true
handle: directors
name: Directors
propagationMethod: all
siteSettings:
  5667283f-37d8-4356-b040-3a9ce12ff30d: # Esperance Historical Museum
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 66756266-5dbd-4584-8d2a-6b0f2b5fc11a
type: structure
