tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 253168b7-9422-4862-bc88-407ebc88fce1
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: add67061-06af-45ff-9ce9-f2a5770cef03
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: e7a228b2-d6cb-4297-b487-8be49914c426
        userCondition: null
        warning: null
    name: Content
    uid: ab843e1e-03c3-4b7b-a901-2d866c7391d1
    userCondition: null
